# -*- coding: utf-8 -*-
"""ResNet50_features.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BPOWdOt0TuJK56fwKBPbV1mZUayaySIC
"""

from keras.applications.vgg19 import VGG19

from keras.preprocessing import image

from keras.applications.vgg19 import preprocess_input
from keras.models import Model

import numpy as np

import tensorflow as tf

from tensorflow.keras import Sequential

from keras.layers import Dense
import numpy as np
import pandas as pd

import librosa

import csv
import os

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.applications.resnet50 import ResNet50
from keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input
from keras.models import Model
import numpy as np
import tensorflow as tf
from tensorflow.keras import Sequential
from keras.layers import Dense
# define the CNN network
# Here we are using 19 layer CNN -VGG19 and initialising it
# with pretrained imagenet weights
base_model = ResNet50(weights='imagenet')
print(base_model.summary())

from tensorflow.keras.utils import load_img
from keras.preprocessing import image
import keras
import keras.utils
from tensorflow.keras.preprocessing.image import img_to_array
import tensorflow.compat.v2 as tf
# like the block4 pooling layer in VGG19 
model = Model(inputs=base_model.input, outputs=base_model.get_layer('block4_pool').output) 
# load an image and preprocess it 
img_path = '/content/drive/MyDrive/dataset/ASVspoof2021/1-61534-A-27.png' 
img = load_img(img_path, target_size=(224, 224)) 
x = img_to_array(img) 
x = np.expand_dims(x, axis=0) 
x = preprocess_input(x) 
# get the features 
block4_pool_features = model.predict(x) 
print(model.predict(x))

import tensorflow as tf
from tensorflow.keras import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(512))
features = model.predict(x)
print(features)

from keras.preprocessing import image
import os
from os import listdir
import glob
import cv2
from pathlib import Path

# get the path/directory
folder_dir = "/content/drive/MyDrive/dataset/ASVspoof2021"
files = Path(folder_dir).glob('*.png')
print(files)
for images in files:
  print(images)
  img = load_img(images)
  x = img_to_array(img)
  print(x.shape)
  x = cv2.resize(x, dsize=(224,224), interpolation=cv2.INTER_CUBIC)
  x = np.expand_dims(x, axis=0)
  x = preprocess_input(x)
  # get the features
  fc1_features = model.predict(x)
  #flatten_features = model.predict(x)
  print(model.predict(x), files)